#61 fix gzero social
GrupaZero/social pull request #6
Opened 2017-03-21 11:42 UTC by michalstrzelecki

Fix gzero social to work with platform, laravel 5.3.

2017-03-21 11:43 UTC, michalstrzelecki commented
In `Fix readme.` commit I actually change two repos to:

- "gzero/core": "dev-master@dev",
- "gzero/entity": "dev-master@dev",

2017-03-21 15:05 UTC, AdrianSkierniewski requested changes

2017-03-21 15:05 UTC, AdrianSkierniewski commented on src/resources/views/connectedServices.blade.php
> +                                'domain'   => config('app.name')
Why we're using same value for siteName & domain here?

2017-03-23 11:16 UTC, AdrianSkierniewski approved these changes

2017-03-23 11:16 UTC, merged